FROM python:3.10

# Install your package from PyPI
RUN pip install async-http-server==0.1.8


# Run module (your package must have __main__.py or entrypoint)
# CMD ["python", "-m", "async_server"]
CMD ["python3", "/usr/local/lib/python3.10/site-packages/async_http_server/async_server.py"]
